version: '3.8'

services:
# Development container.
# Runs in debug mode and live-reloading on every source file update.
  app-dev:
    hostname: app-dev
    restart: unless-stopped
# if use private libs uncomment this
#      args:
#        - GITHUB_TOKEN=${GITHUB_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8888:${APP_PORT}
    env_file:
      - .env
    volumes:
      - ./:/app
