name: Testing PR Develop

on:
  pull_request:
    branches: [ develop ]

jobs:
  testing_pr_develop:
    name: Check Develop PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Node LTS
        id: install_node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        id: install_deps
        run: yarn install --frozen-lockfile

      - name: Typescript check
        id: test_ts
        run: yarn dev:check

      - name: ESLint check
        id: test_eslint
        run: yarn dev:lint

      - name: Run tests
        id: run_tests
        run: yarn test --passWithNoTests
